version: "2"
linters:
  default: standard
  exclusions:
    generated: lax
    paths:
      - ref
      - scratch
      - clients
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
