run:
  timeout: 5m
  skip-dirs:
    - ref
    - scratch
    - clients

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-use-default: false
