//! Codex harness driver.
//!
//! Drives `codex app-server --listen stdio://` — the JSON-lines RPC
//! surface (not JSON-RPC 2.0: no `jsonrpc` field). Behavior ported from
//! davidondrej/cloudroom-core `src/runtime/codex.rs` (Apache-2.0) and the
//! schema generated by the local `codex app-server generate-json-schema`
//! (0.148.0): `initialize` → `initialized` → `thread/start|resume`, turns
//! via `turn/start` (`clientUserMessageId`, text items), boundaries from
//! `turn/completed` with `TurnStatus = completed | interrupted | failed |
//! inProgress`, approvals as **server→client requests**
//! (`commandExecution/requestApproval`, `applyPatch/requestApproval`)
//! answered with `accept | acceptForSession | decline | cancel`.

pub mod driver;
pub mod resolve;

use std::path::Path;

pub use driver::{Driver, models};
pub use openremote_harness::{DriverError, DriverEvent, Resolution, SpawnOptions};

/// Find the Codex CLI. `override` wins (tests point it at the fixture
/// agent); otherwise `codex` on PATH (the npm `codex.js` through node on
/// Windows — the `.cmd` shim is unspawnable).
pub fn resolve_codex(override_path: Option<&Path>) -> Resolution {
    resolve::resolve_impl(override_path.map(std::path::PathBuf::from))
}
